### PR TITLE
Add Build enviroment for windows executable

### PR DESCRIPTION
**Pull request by psalic**

### CODE REVIEW

**Comment by lundmar** [comment]
FYI - you should have write access to this repository. Feel free to push future commits directly.

**Comment by psalic** [comment]
ok, I will
I will prepare test release. It will still be with number 2.7 even that is last software. Later can be deleted .For new release submodules needs to be updated.

**Comment by lundmar** [comment]
I'll let you have all the time you need to prepare your test release of the windows installer.

When you feel the windows installer setup is ready I can prepare for a lxi-tools v2.8 and release notes in which we can announce the availability of the windows-installer.

**Comment by lundmar** [comment]
FYI - I just tried the windows installer from the CI pipeline and it works surprisingly well. I mean, I shouldn't too surprised but it is fun to see how well the GTK4 toolkit behaves even on Windows.

I have a 42" 4k monitor so I normally don't use scaling but in Windows it looks like I need to enable 150% scaling else text in the lxi-gui becomes hard to read.

This is how it looks without scaling:
Screenshot From 2024-10-01 19-18-18

And with 150% scaling:
image

This also makes it look almost identical to how it looks in Linux (lxi-gui running on Ubuntu Gnome DE on the right, windows on the left side):

Screenshot From 2024-10-01 19-30-10

The only place I see problems with text readability is in the scripts pane:

Screenshot From 2024-10-01 19-34-25

Here the font is definitely harder to read on Windows so we may have to look into that.

**Comment by psalic** [comment]
test release is ready
Yes, its hard to read. But in light mode is still better. Othervise it works pretty well

**Comment by lundmar** [comment]
> test release is ready

Great, then I can start preparing new releases of liblxi and lxi-tools. I plan to do this the coming weekend as I'm currently quite busy with another job.

**Comment by psalic** [comment]
> > test release is ready
> 
> Great, then I can start preparing new releases of liblxi and lxi-tools. I plan to do this the coming weekend as I'm currently quite busy with another job.

Work is done. Prepare release when you have time, Then we just need to update submodules on this repository and we can make new release build

**Pull request merged**
